### ISSUE TITLE
debconf-utils not installed

### ISSUE THREAD

**Issue by acurus-puppetmaster** [smoeding/puppet-debconf#5] opened 2018-04-17 02:04 UTC
Under Ubuntu 16.04 debconf-utils package isn't installed automatically.

This module doesn't install it, so puppet runs often cause issues such as 

```
Error: /Stage[main]/Timezone/Exec[update_debconf area]: Could not evaluate: Could not find command 'debconf-get-selections'
Error: /Stage[main]/Timezone/Exec[update_debconf zone]: Could not evaluate: Could not find command 'debconf-get-selections'
```

**Comment by smoeding** [comment] 2018-04-17 16:40
The debconf package doesn't use the `debconf-get-selections` binary.
So your error is not caused by this package.

Look closer at the error message:
The `timezone` module declares two exec resources named `update_debconf area` and `update_debconf zone`. These exec resources try to run the missing program. I don't know which timezone package you are using but this can only be fixed by the author of that timezone package.

**Comment by smoeding** [comment] 2018-04-19 15:58
As documented this is not caused by the debconf package but by the used timezone package.

**Closed by smoeding** 2018-04-19 15:58 UTC
